### PR TITLE
Add base image for Ubuntu 20.04 Focal Fossa

### PR DESCRIPTION
**Pull request by liamoreilly**
I have created a base image for Focal Fossa which is the current Ubuntu LTS.

### CODE REVIEW

**Comment by james-perretta** [comment]
Thanks for this! I'll likely merge it on Monday.

**Comment by liamoreilly** [comment]
Okay, there may be an issue here. For focal "echo $BASH" results in 
usr/bin/bash
where as on bionic it results in
/bin/bash

I think autograder does not like this and fails a sanbox image build with the error:
Custom images may not use the CMD directive. Expected ["/bin/bash"] but was "['bash']".

On focal both /bin/bash and /usr/bin/bash are identical files.

**Comment by james-perretta** [comment]
(Edit edit) Ok, I think I got it right this time:

I think the quickest fix would be to add `CMD ["/bin/bash"]` (the brackets and quotes are required) to the end of the dockerfile--I think `/usr/bin/bash` is just a symlink to `/bin/bash`.

I can also update the Dockerfile snippet in the readme to include `CMD ["/bin/bash"]` with a note about it.

**Comment by james-perretta** [comment]
Applied the changes discussed here in #3

**Pull request closed without merging**
